### PR TITLE
certtoken is not required

### PR DESCRIPTION
**Pull request by gnowxilef**

### CODE REVIEW

**Comment by mahtin** [comment]
@gnowxilef - the ```certtoken``` is used for the [/certificates](https://api.cloudflare.com/#cloudflare-ca-properties) API call. Please try out some of these calls; they are very useful for securing (for free) your origin. Please read [Introducing CloudFlare Origin CA](https://blog.cloudflare.com/cloudflare-ca-encryption-origin/) plus the API documentation linked above.

Let me know if that makes sense.

Martin

**Comment by gnowxilef** [comment]
sure, but it is not required for most endpoints. maybe the endpoints that require it should check that certtoken exists?

**Comment by mahtin** [comment]
I think this is a programming style issue. I grabbed this mindset from you and expanded upon it. I actually like it. For example, only the ```/certificates``` API call uses ```certtoken``` today; but that may change.
```
$ egrep _add_with_cert_auth CloudFlare/api_v4.py
            self._add_with_cert_auth(self._base, "certificates"))
$ 
```
 The ```_add_with_cert_auth``` ends up using ```call_with_certauth``` which is the only place in the codebase that needs to check ```certtoken```.
```
        def call_with_certauth(self, method,
            ...
            if self.certtoken is '':
                raise CloudFlareAPIError(0, 'no cert token defined')
            headers = {
                'X-Auth-User-Service-Key': self.certtoken,
                'Content-Type': 'application/json'
            }
            ...
```
I think this is as efficient as is needed.

Going back to your initial PR and the change you requested. Note that the code for ```certtoken``` checking is in the class init function. This simply makes this option in-line with account info. It's normally allocated on a per-account basis. This seems the right way to implement this. 

I will discuss this in-house and see what people think.

More later.

Martin

**Comment by gnowxilef** [comment]
i see. i am actually referring to the case where if i don't specify a certtoken in the config file, the entire program errors out. (afaict, my pr remove that check upon entering the program. the program errors out immediately if the certtoken is not found in the config file.)

do we want the program to error out immediately if there is no certtoken in the config file? (especially since currently only one endpoint uses it.)

**Comment by mahtin** [comment]
I just tested it with and without a config file; with ```certtoken``` and without ```certtoken``` in the config file; even with ```certtoken``` as an empty string. I could not reproduce a failure like yours. In fact the opposite - it did what I expected it too do. I did realize that [CloudFlare/cloudflare.py](https://github.com/cloudflare/python-cloudflare/blob/master/CloudFlare/cloudflare.py) needed a change in order to correctly handle a missing ```certtoken``` value; but that would have been caught by the API call:
```
-            if self.certtoken is '':
+            if self.certtoken is '' or self.certtoken is None:
```
I tested this on API calls that used and didn't use the certtoken in a header. All were fine.

What environment are you running in? In my care, my development platform is macOS El Capitan 10.11.6 with Xcode 8.1 and Python 2.7.10 as default. I have Python 3.5.2 loaded up via Homebrew 1.0.9; however I'm not fully working on Python 3 yet.

**Comment by gnowxilef** [comment]
odd, it now works as well. i am on debian 8.6. i used it with both python 2.7.9 and 3.4.2. i'll close this PR for now since it does seem to work as expected.

**Pull request closed without merging**
