### PR TITLE
doc fix.

### PR DESCRIPTION
**Pull request by hlx98007**
I found this problem in pypi 1.1.0 version of cloudflare. The program itself is running fine but the doc has a couple of minor problems.

### CODE REVIEW

**Comment by fishpen0** [comment]
Please approve this PR, this doc typo is really annoying.

**Comment by mahtin** [comment]
Yikes. Yes - that's a real bug in the code; however the documentation also needs updating. I will first accept this PR and then go fix the code (which is a quick one-liner!)

**Comment by mahtin** [comment]
Merged! (and fixed code) I will now edit the README to explain what's going on. Good catch!

**Comment by hlx98007** [comment]
Thanks!

**Pull request merged**
