### PR TITLE
Requests timeouts and retries

### PR DESCRIPTION
**Pull request by dkoston**
Overview
---------
* Sets a global request timeout for all calls to Cloudflare API.
* Allows configuration of that timeout  through `global_request_timeout` option on `Cloudflare()`
* For requests using sessions, adds 5 retries on connection errors.
* Allows configuration of retries through `max_request_retries` option on `Cloudflare()`

Why
------
We are experiencing some requests hanging for over 2 minutes which trips our gunicorn timeout. It is also best practices to have a timeout on each http request. Retries add resiliency to network issues.

### CODE REVIEW

**Comment by mahtin** [comment]
@dkoston - Thanks! This timeout capability has been somewhat overdue to be coded up. Happy to take your edits.

I'm AFK till later-today/tonight but I'll work out how to merge it later ('cause I've got some unrelated pending updates in the pipeline). Stay tuned. 

BTW: I'll forgo the " vs ' used for strings debate! 😄

Plus: Thanks for adding a `pytest` to the Makefile. Also somewhat overdue!

**Comment by dkoston** [comment]
Thanks @mahtin ! I adjusted any non-interpolated strings back to single quote. Sorry about that. Been writing mostly go these days where single quotes are runes.

**Comment by dkoston** [comment]
Sure! Done.

**Comment by mahtin** [comment]
@dkoston - It's now up as version `2.12.2` via https://pypi.org/project/cloudflare/ - looks good. I didn't remove the `pytest` entries in `requirements.txt` or `setup.cfg` so that the end-user does not need to install that package. I may remove it sometime soon. No rush.

Thank you for your code! A feature that is somewhat overdue.

**Pull request merged**
